<a href="https://colab.research.google.com/github/PhoniciaAnne/Numpy-python/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [5]:
a = np.array(([1,2,3,4],[2,3,4,5]))
print(a)
b = np.arange(4)
print(b)
c = np.multiply(a,b)
print(c)


[[1 2 3 4]
 [2 3 4 5]]
[0 1 2 3]
[[ 0  2  6 12]
 [ 0  3  8 15]]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
A = np.random.uniform([0,1,1536])
print(A)

[  0.88341906   1.         783.11534524]


In [56]:
New = []
for i in range(10):
   a = np.random.uniform(0,1,1536)
   New.append(a)

print(New)


np.shape(New)


[array([0.72306322, 0.35164383, 0.49115435, ..., 0.67248297, 0.54531224,
       0.52919512]), array([0.80816287, 0.126836  , 0.4596654 , ..., 0.24068022, 0.76788716,
       0.39390372]), array([0.92005518, 0.67224512, 0.14177863, ..., 0.75929512, 0.72108787,
       0.61412708]), array([0.16625902, 0.40269669, 0.29036929, ..., 0.6580214 , 0.46683204,
       0.4743816 ]), array([0.86181059, 0.44980796, 0.10582407, ..., 0.2778205 , 0.1679513 ,
       0.27664628]), array([0.01428288, 0.5407587 , 0.13023533, ..., 0.34346391, 0.34885626,
       0.30426618]), array([0.77938679, 0.22798521, 0.71642333, ..., 0.36091256, 0.64318717,
       0.63534391]), array([0.27979651, 0.18706981, 0.19007083, ..., 0.77871499, 0.90551067,
       0.38816559]), array([0.63038726, 0.95937992, 0.66687902, ..., 0.86098325, 0.72855522,
       0.53774899]), array([0.83977949, 0.84697255, 0.54067629, ..., 0.75233264, 0.00546092,
       0.31673861])]


(10, 1536)

In [57]:
Ans= []

for i in range(10):
   a = np.random.uniform(0,1,1536)
   Ans.append(a)

print(Ans)




[array([0.67497869, 0.26485983, 0.28088198, ..., 0.42951952, 0.42486644,
       0.3910711 ]), array([0.52454148, 0.44437397, 0.49622128, ..., 0.49507618, 0.02059178,
       0.9942281 ]), array([0.76973637, 0.86974169, 0.21013876, ..., 0.53251543, 0.42758964,
       0.06067818]), array([0.29233356, 0.06697939, 0.00705848, ..., 0.01067163, 0.21507727,
       0.22211887]), array([0.03879157, 0.2069649 , 0.73605048, ..., 0.71606507, 0.90886377,
       0.30571204]), array([6.39749229e-01, 7.30930914e-01, 1.32249131e-01, ...,
       2.36091555e-04, 2.80033513e-01, 9.83984966e-01]), array([0.59179609, 0.59169413, 0.12251077, ..., 0.50316838, 0.25059699,
       0.64213693]), array([0.00364684, 0.25353101, 0.61178674, ..., 0.1277527 , 0.20607674,
       0.68063859]), array([0.81105184, 0.4042419 , 0.9289688 , ..., 0.13677965, 0.16296826,
       0.38145139]), array([0.31973849, 0.32733382, 0.4476287 , ..., 0.56021579, 0.50819836,
       0.8021144 ])]


In [59]:
dot_product = np.dot(New, np.array(Ans).T)
print(dot_product)

[[392.33387362 376.86295328 382.29485398 379.43564185 374.04611707
  379.6836526  375.0359124  378.39351116 371.78177097 371.65687092]
 [394.77854794 391.36185954 396.98002572 393.26792384 395.26286762
  393.14701989 392.07588837 397.6078399  393.84764616 383.99650341]
 [386.85129366 387.7431956  390.39103686 386.34083678 388.53146866
  390.62323439 382.38738828 391.85853643 386.34300258 376.77999375]
 [378.04986662 375.49935074 377.56842241 377.85022236 378.12238724
  379.46783642 379.15963469 380.26031368 378.75895048 374.19544954]
 [377.16836591 377.69245186 375.34703913 374.29003151 369.71382701
  372.4269535  369.88622931 375.0948421  371.9544813  365.43523993]
 [379.34440779 379.87096549 380.96381676 385.81501499 381.35165994
  379.80007366 377.91059511 380.92906449 378.48582099 369.86621234]
 [388.17979038 383.59315062 383.08094123 381.921755   386.15445039
  384.01651791 379.25449435 385.1443696  382.01293362 373.07086125]
 [378.73171028 370.84711608 383.38654661 374.8174048  3

In [60]:
from numpy.linalg import norm
result = dot_product/(norm(New)*norm(Ans))
print(result)

[[0.0771406  0.07409871 0.07516673 0.07460455 0.07354486 0.07465331
  0.07373947 0.07439964 0.07309965 0.07307509]
 [0.07762127 0.07694948 0.07805412 0.07732425 0.07771649 0.07730048
  0.07708987 0.07817756 0.07743823 0.0755013 ]
 [0.07606261 0.07623798 0.0767586  0.07596225 0.07639297 0.07680425
  0.07518492 0.07704713 0.07596267 0.0740824 ]
 [0.07433208 0.0738306  0.07423742 0.07429282 0.07434634 0.07461088
  0.07455028 0.07476669 0.0744715  0.07357422]
 [0.07415876 0.0742618  0.07380065 0.07359282 0.07269305 0.0732265
  0.07272694 0.07375106 0.0731336  0.07185179]
 [0.07458661 0.07469014 0.07490502 0.07585886 0.07498128 0.0746762
  0.07430469 0.07489818 0.07441779 0.07272301]
 [0.07632382 0.075422   0.07532129 0.07509337 0.0759256  0.07550524
  0.07456893 0.075727   0.07511129 0.07335311]
 [0.07446614 0.07291587 0.07538137 0.07369651 0.0741405  0.07420519
  0.07449276 0.07358722 0.07289053 0.0716312 ]
 [0.07683796 0.07347675 0.07476122 0.07443844 0.07348248 0.07434048
  0.07263002 0

In [121]:
max = np.max(result)
print(max)

0.07817756156543655


In [134]:
static_array = [[np.random.uniform(0,1) for i in range(1536)] for _ in range(10)]
print(static_array)


[[0.12392446371466781, 0.01613138822059279, 0.7871479382864938, 0.9069101370066193, 0.3419776452724197, 0.8947401391327894, 0.1669580505047833, 0.9248873527686107, 0.39871682966971866, 0.6573880310955585, 0.3928050761555206, 0.6466566019841976, 0.7230567023843533, 0.8955351902937976, 0.4900001166333703, 0.8813177067450111, 0.2813123809520264, 0.726239838881433, 0.5799459823884442, 0.6642194139180077, 0.37651072035410127, 0.977180252574497, 0.6962704673692254, 0.5770932739175069, 0.7413582076540739, 0.7683021506094598, 0.6575415788512722, 0.355962919884555, 0.4790169595779803, 0.20996456775265737, 0.1571567374665339, 0.034629285640991436, 0.22484808882214136, 0.9837125113856743, 0.3895363722934809, 0.46787397176728485, 0.7957397412044265, 0.6914406753983249, 0.7194570852840735, 0.40492717775965836, 0.3526819722185641, 0.9290787912000118, 0.8468989138566136, 0.6902597959906698, 0.8908073471361284, 0.5090492795659977, 0.6396876669092368, 0.3120609274802535, 0.043698613326653035, 0.7248819

In [118]:
def get_dot_product(arr1,arr2):
  return np.dot(arr1,arr2)

def get_cosine_similarity(arr1, arr2):
    dot_product = np.dot(arr1, arr2)
    norm_arr1 = np.linalg.norm(arr1)
    norm_arr2 = np.linalg.norm(arr2)
    cosine_similarity = dot_product / (norm_arr1 * norm_arr2)
    return cosine_similarity

In [133]:
# b =[]
# for i in range(10):
#     a =[np.random.uniform(0,1) for i in range(1536)]
#     b.append(a)


In [119]:
for test in range(10):
  test_example = [np.random.uniform(0,1) for _ in range(1536)]

  dot_product_results = []
  cosine_similarity_results = []
  for trained_example in static_array:
    dot_product = get_dot_product(test_example,trained_example)
    cosine_similarity = get_cosine_similarity(test_example,trained_example)
    dot_product_results.append(dot_product)
    cosine_similarity_results.append(cosine_similarity)
  print("MAximum cosine Similarity",np.max(cosine_similarity_results))
  print("MAximum dot product",np.max(dot_product_results))


MAximum cosine Similarity 0.7615860947227183
MAximum dot product 390.3731820586289
MAximum cosine Similarity 0.7587464098020568
MAximum dot product 397.7598927234638
MAximum cosine Similarity 0.7553655843776551
MAximum dot product 385.5277823640811
MAximum cosine Similarity 0.7657937052411095
MAximum dot product 397.6199450147799
MAximum cosine Similarity 0.7511894251723775
MAximum dot product 381.99144669805105
MAximum cosine Similarity 0.7717017589739933
MAximum dot product 404.9334663262021
MAximum cosine Similarity 0.7661443300888924
MAximum dot product 398.23732190426665
MAximum cosine Similarity 0.7756985301593445
MAximum dot product 396.24407115748585
MAximum cosine Similarity 0.7566147856550843
MAximum dot product 394.88813701026555
MAximum cosine Similarity 0.7556410361929167
MAximum dot product 380.80621628382784
